version: '2'

services:
  postgres:
    image: 'postgres:9.4.5'
    environment:
      POSTGRES_USER: 'mobydock'
      POSTGRES_PASSWORD: 'yourpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:5.0.8'
    volumes:
      - 'redis:/data'

  mobydock:
    build: '.'
    depends_on:
      - 'postgres'
      - 'redis'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    ports:
      - '8000:8000'
  
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro



volumes:
  postgres: {}
  redis: {}
