apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    env: prod
    app: main
    tier: frontend
    owner: Yurii
spec:
  containers:
    - name: container-nginx
      image: nginx:latest
      ports:
        - containerPort: 80