version: '3.4'
services:
    zookeeper:
        container_name: "zookeeper_test"
        restart: on-failure
        image: confluentinc/cp-zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 4151
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - kafka
        ports:
            - "4151:2181"
    kafka:
        container_name: "kafka_test"
        image: confluentinc/cp-kafka
        environment:
           KAFKA_ZOOKEEPER_CONNECT: zookeeper_test:2181
           KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
        networks:
            - kafka
        ports:
            - "39092:39092"
        depends_on:
          - zookeeper
    
networks:
  kafka:
    driver: bridge